/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppErrorPage: typeof import('./src/components/app-error/AppErrorPage.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    Collapsible: typeof import('./src/components/ui/collapsible/Collapsible.vue')['default']
    CollapsibleContent: typeof import('./src/components/ui/collapsible/CollapsibleContent.vue')['default']
    CollapsibleTrigger: typeof import('./src/components/ui/collapsible/CollapsibleTrigger.vue')['default']
    Dialog: typeof import('./src/components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./src/components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./src/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./src/components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./src/components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./src/components/ui/dialog/DialogHeader.vue')['default']
    DialogScrollContent: typeof import('./src/components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./src/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./src/components/ui/dialog/DialogTrigger.vue')['default']
    EmptyState: typeof import('./src/components/projects/EmptyState.vue')['default']
    FilterSection: typeof import('./src/components/projects/filter-section/FilterSection.vue')['default']
    Header: typeof import('./src/components/journal/Header.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    JournalHeader: typeof import('./src/components/journal/JournalHeader.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    ProjectGridView: typeof import('./src/components/projects/ProjectGridView.vue')['default']
    ProjectListView: typeof import('./src/components/projects/ProjectListView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./src/components/ui/scroll-area/ScrollArea.vue')['default']
    ScrollBar: typeof import('./src/components/ui/scroll-area/ScrollBar.vue')['default']
    Select: typeof import('./src/components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./src/components/ui/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./src/components/ui/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./src/components/ui/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./src/components/ui/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./src/components/ui/select/SelectLabel.vue')['default']
    SelectScrollDownButton: typeof import('./src/components/ui/select/SelectScrollDownButton.vue')['default']
    SelectScrollUpButton: typeof import('./src/components/ui/select/SelectScrollUpButton.vue')['default']
    SelectSeparator: typeof import('./src/components/ui/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./src/components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./src/components/ui/select/SelectValue.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    TimelineHeader: typeof import('./src/components/journal/TimelineHeader.vue')['default']
  }
}
