"""remove constriant on name

Revision ID: f162846e6c36
Revises: b101d0fa4705
Create Date: 2025-05-01 11:51:38.846931

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f162846e6c36"
down_revision: Union[str, None] = "b101d0fa4705"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_technology_name", table_name="technology")
    op.create_index(op.f("ix_technology_name"), "technology", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_technology_name"), table_name="technology")
    op.create_index("ix_technology_name", "technology", ["name"], unique=1)
    # ### end Alembic commands ###
